/*
Champion data taken from https://github.com/bartdebever/lol-champions/;
Currently missing: Neeko
*/
var champs = {
"aatrox":{"id":266,"name":"Aatrox","internalName":"Aatrox","title":"the Darkin Blade"},
"ahri":{"id":103,"name":"Ahri","internalName":"Ahri","title":"the Nine-Tailed Fox"},
"akali":{"id":84,"name":"Akali","internalName":"Akali","title":"the Rogue Assassin"},
"alistar":{"id":12,"name":"Alistar","internalName":"Alistar","title":"the Minotaur"},
"amumu":{"id":32,"name":"Amumu","internalName":"Amumu","title":"the Sad Mummy"},
"anivia":{"id":34,"name":"Anivia","internalName":"Anivia","title":"the Cryophoenix"},
"annie":{"id":1,"name":"Annie","internalName":"Annie","title":"the Dark Child"},
"ashe":{"id":22,"name":"Ashe","internalName":"Ashe","title":"the Frost Archer"},
"aurelionsol":{"id":136,"name":"Aurelion Sol","internalName":"AurelionSol","title":"The Star Forger"},
"azir":{"id":268,"name":"Azir","internalName":"Azir","title":"the Emperor of the Sands"},
"bard":{"id":432,"name":"Bard","internalName":"Bard","title":"the Wandering Caretaker"},
"blitzcrank":{"id":53,"name":"Blitzcrank","internalName":"Blitzcrank","title":"the Great Steam Golem"},
"brand":{"id":63,"name":"Brand","internalName":"Brand","title":"the Burning Vengeance"},
"braum":{"id":201,"name":"Braum","internalName":"Braum","title":"the Heart of the Freljord"},
"caitlyn":{"id":51,"name":"Caitlyn","internalName":"Caitlyn","title":"the Sheriff of Piltover"},
"camille":{"id":164,"name":"Camille","internalName":"Camille","title":"the Steel Shadow"},
"cassiopeia":{"id":69,"name":"Cassiopeia","internalName":"Cassiopeia","title":"the Serpent's Embrace"},
"chogath":{"id":31,"name":"Cho'Gath","internalName":"Chogath","title":"the Terror of the Void"},
"corki":{"id":42,"name":"Corki","internalName":"Corki","title":"the Daring Bombardier"},
"darius":{"id":122,"name":"Darius","internalName":"Darius","title":"the Hand of Noxus"},
"diana":{"id":131,"name":"Diana","internalName":"Diana","title":"Scorn of the Moon"},
"draven":{"id":119,"name":"Draven","internalName":"Draven","title":"the Glorious Executioner"},
"dr.mundo":{"id":36,"name":"Dr. Mundo","internalName":"DrMundo","title":"the Madman of Zaun"},
"ekko":{"id":245,"name":"Ekko","internalName":"Ekko","title":"the Boy Who Shattered Time"},
"elise":{"id":60,"name":"Elise","internalName":"Elise","title":"the Spider Queen"},
"evelynn":{"id":28,"name":"Evelynn","internalName":"Evelynn","title":"Agony's Embrace"},
"ezreal":{"id":81,"name":"Ezreal","internalName":"Ezreal","title":"the Prodigal Explorer"},
"fiddlesticks":{"id":9,"name":"Fiddlesticks","internalName":"Fiddlesticks","title":"the Harbinger of Doom"},
"fiora":{"id":114,"name":"Fiora","internalName":"Fiora","title":"the Grand Duelist"},
"fizz":{"id":105,"name":"Fizz","internalName":"Fizz","title":"the Tidal Trickster"},
"galio":{"id":3,"name":"Galio","internalName":"Galio","title":"the Colossus"},
"gangplank":{"id":41,"name":"Gangplank","internalName":"Gangplank","title":"the Saltwater Scourge"},
"garen":{"id":86,"name":"Garen","internalName":"Garen","title":"The Might of Demacia"},
"gnar":{"id":150,"name":"Gnar","internalName":"Gnar","title":"the Missing Link"},
"gragas":{"id":79,"name":"Gragas","internalName":"Gragas","title":"the Rabble Rouser"},
"graves":{"id":104,"name":"Graves","internalName":"Graves","title":"the Outlaw"},
"hecarim":{"id":120,"name":"Hecarim","internalName":"Hecarim","title":"the Shadow of War"},
"heimerdinger":{"id":74,"name":"Heimerdinger","internalName":"Heimerdinger","title":"the Revered Inventor"},
"illaoi":{"id":420,"name":"Illaoi","internalName":"Illaoi","title":"the Kraken Priestess"},
"irelia":{"id":39,"name":"Irelia","internalName":"Irelia","title":"the Blade Dancer"},
"ivern":{"id":427,"name":"Ivern","internalName":"Ivern","title":"the Green Father"},
"janna":{"id":40,"name":"Janna","internalName":"Janna","title":"the Storm's Fury"},
"jarvaniv":{"id":59,"name":"Jarvan IV","internalName":"JarvanIV","title":"the Exemplar of Demacia"},
"jax":{"id":24,"name":"Jax","internalName":"Jax","title":"Grandmaster at Arms"},
"jayce":{"id":126,"name":"Jayce","internalName":"Jayce","title":"the Defender of Tomorrow"},
"jhin":{"id":202,"name":"Jhin","internalName":"Jhin","title":"the Virtuoso"},
"jinx":{"id":222,"name":"Jinx","internalName":"Jinx","title":"the Loose Cannon"},
"kaisa":{"id":145,"name":"Kai'Sa","internalName":"Kaisa","title":"Daughter of the Void"},
"kalista":{"id":429,"name":"Kalista","internalName":"Kalista","title":"the Spear of Vengeance"},
"karma":{"id":43,"name":"Karma","internalName":"Karma","title":"the Enlightened One"},
"karthus":{"id":30,"name":"Karthus","internalName":"Karthus","title":"the Deathsinger"},
"kassadin":{"id":38,"name":"Kassadin","internalName":"Kassadin","title":"the Void Walker"},
"katarina":{"id":55,"name":"Katarina","internalName":"Katarina","title":"the Sinister Blade"},
"kayle":{"id":10,"name":"Kayle","internalName":"Kayle","title":"The Judicator"},
"kayn":{"id":141,"name":"Kayn","internalName":"Kayn","title":"the Shadow Reaper"},
"kennen":{"id":85,"name":"Kennen","internalName":"Kennen","title":"the Heart of the Tempest"},
"khazix":{"id":121,"name":"Kha'Zix","internalName":"Khazix","title":"the Voidreaver"},
"kindred":{"id":203,"name":"Kindred","internalName":"Kindred","title":"The Eternal Hunters"},
"kled":{"id":240,"name":"Kled","internalName":"Kled","title":"the Cantankerous Cavalier"},
"kogmaw":{"id":96,"name":"Kog'Maw","internalName":"KogMaw","title":"the Mouth of the Abyss"},
"leblanc":{"id":7,"name":"LeBlanc","internalName":"Leblanc","title":"the Deceiver"},
"leesin":{"id":64,"name":"Lee Sin","internalName":"LeeSin","title":"the Blind Monk"},
"leona":{"id":89,"name":"Leona","internalName":"Leona","title":"the Radiant Dawn"},
"lissandra":{"id":127,"name":"Lissandra","internalName":"Lissandra","title":"the Ice Witch"},
"lucian":{"id":236,"name":"Lucian","internalName":"Lucian","title":"the Purifier"},
"lulu":{"id":117,"name":"Lulu","internalName":"Lulu","title":"the Fae Sorceress"},
"lux":{"id":99,"name":"Lux","internalName":"Lux","title":"the Lady of Luminosity"},
"malphite":{"id":54,"name":"Malphite","internalName":"Malphite","title":"Shard of the Monolith"},
"malzahar":{"id":90,"name":"Malzahar","internalName":"Malzahar","title":"the Prophet of the Void"},
"maokai":{"id":57,"name":"Maokai","internalName":"Maokai","title":"the Twisted Treant"},
"masteryi":{"id":11,"name":"Master Yi","internalName":"MasterYi","title":"the Wuju Bladesman"},
"missfortune":{"id":21,"name":"Miss Fortune","internalName":"MissFortune","title":"the Bounty Hunter"},
"wukong":{"id":62,"name":"Wukong","internalName":"MonkeyKing","title":"the Monkey King"},
"mordekaiser":{"id":82,"name":"Mordekaiser","internalName":"Mordekaiser","title":"the Iron Revenant"},
"morgana":{"id":25,"name":"Morgana","internalName":"Morgana","title":"Fallen Angel"},
"nami":{"id":267,"name":"Nami","internalName":"Nami","title":"the Tidecaller"},
"nasus":{"id":75,"name":"Nasus","internalName":"Nasus","title":"the Curator of the Sands"},
"nautilus":{"id":111,"name":"Nautilus","internalName":"Nautilus","title":"the Titan of the Depths"},
"nidalee":{"id":76,"name":"Nidalee","internalName":"Nidalee","title":"the Bestial Huntress"},
"nocturne":{"id":56,"name":"Nocturne","internalName":"Nocturne","title":"the Eternal Nightmare"},
"nunuwillump":{"id":20,"name":"Nunu & Willump","internalName":"Nunu","title":"the Boy and His Yeti"},
"olaf":{"id":2,"name":"Olaf","internalName":"Olaf","title":"the Berserker"},
"orianna":{"id":61,"name":"Orianna","internalName":"Orianna","title":"the Lady of Clockwork"},
"ornn":{"id":516,"name":"Ornn","internalName":"Ornn","title":"The Fire below the Mountain"},
"pantheon":{"id":80,"name":"Pantheon","internalName":"Pantheon","title":"the Artisan of War"},
"poppy":{"id":78,"name":"Poppy","internalName":"Poppy","title":"Keeper of the Hammer"},
"pyke":{"id":555,"name":"Pyke","internalName":"Pyke","title":"the Bloodharbor Ripper"},
"quinn":{"id":133,"name":"Quinn","internalName":"Quinn","title":"Demacia's Wings"},
"rakan":{"id":497,"name":"Rakan","internalName":"Rakan","title":"The Charmer"},
"rammus":{"id":33,"name":"Rammus","internalName":"Rammus","title":"the Armordillo"},
"reksai":{"id":421,"name":"Rek'Sai","internalName":"RekSai","title":"the Void Burrower"},
"renekton":{"id":58,"name":"Renekton","internalName":"Renekton","title":"the Butcher of the Sands"},
"rengar":{"id":107,"name":"Rengar","internalName":"Rengar","title":"the Pridestalker"},
"riven":{"id":92,"name":"Riven","internalName":"Riven","title":"the Exile"},
"rumble":{"id":68,"name":"Rumble","internalName":"Rumble","title":"the Mechanized Menace"},
"ryze":{"id":13,"name":"Ryze","internalName":"Ryze","title":"the Rune Mage"},
"sejuani":{"id":113,"name":"Sejuani","internalName":"Sejuani","title":"Fury of the North"},
"shaco":{"id":35,"name":"Shaco","internalName":"Shaco","title":"the Demon Jester"},
"shen":{"id":98,"name":"Shen","internalName":"Shen","title":"the Eye of Twilight"},
"shyvana":{"id":102,"name":"Shyvana","internalName":"Shyvana","title":"the Half-Dragon"},
"singed":{"id":27,"name":"Singed","internalName":"Singed","title":"the Mad Chemist"},
"sion":{"id":14,"name":"Sion","internalName":"Sion","title":"The Undead Juggernaut"},
"sivir":{"id":15,"name":"Sivir","internalName":"Sivir","title":"the Battle Mistress"},
"skarner":{"id":72,"name":"Skarner","internalName":"Skarner","title":"the Crystal Vanguard"},
"sona":{"id":37,"name":"Sona","internalName":"Sona","title":"Maven of the Strings"},
"soraka":{"id":16,"name":"Soraka","internalName":"Soraka","title":"the Starchild"},
"swain":{"id":50,"name":"Swain","internalName":"Swain","title":"the Noxian Grand General"},
"syndra":{"id":134,"name":"Syndra","internalName":"Syndra","title":"the Dark Sovereign"},
"tahmkench":{"id":223,"name":"Tahm Kench","internalName":"TahmKench","title":"the River King"},
"taliyah":{"id":163,"name":"Taliyah","internalName":"Taliyah","title":"the Stoneweaver"},
"talon":{"id":91,"name":"Talon","internalName":"Talon","title":"the Blade's Shadow"},
"taric":{"id":44,"name":"Taric","internalName":"Taric","title":"the Shield of Valoran"},
"teemo":{"id":17,"name":"Teemo","internalName":"Teemo","title":"the Swift Scout"},
"thresh":{"id":412,"name":"Thresh","internalName":"Thresh","title":"the Chain Warden"},
"tristana":{"id":18,"name":"Tristana","internalName":"Tristana","title":"the Yordle Gunner"},
"trundle":{"id":48,"name":"Trundle","internalName":"Trundle","title":"the Troll King"},
"tryndamere":{"id":23,"name":"Tryndamere","internalName":"Tryndamere","title":"the Barbarian King"},
"twistedfate":{"id":4,"name":"Twisted Fate","internalName":"TwistedFate","title":"the Card Master"},
"twitch":{"id":29,"name":"Twitch","internalName":"Twitch","title":"the Plague Rat"},
"udyr":{"id":77,"name":"Udyr","internalName":"Udyr","title":"the Spirit Walker"},
"urgot":{"id":6,"name":"Urgot","internalName":"Urgot","title":"the Dreadnought"},
"varus":{"id":110,"name":"Varus","internalName":"Varus","title":"the Arrow of Retribution"},
"vayne":{"id":67,"name":"Vayne","internalName":"Vayne","title":"the Night Hunter"},
"veigar":{"id":45,"name":"Veigar","internalName":"Veigar","title":"the Tiny Master of Evil"},
"velkoz":{"id":161,"name":"Vel'Koz","internalName":"Velkoz","title":"the Eye of the Void"},
"vi":{"id":254,"name":"Vi","internalName":"Vi","title":"the Piltover Enforcer"},
"viktor":{"id":112,"name":"Viktor","internalName":"Viktor","title":"the Machine Herald"},
"vladimir":{"id":8,"name":"Vladimir","internalName":"Vladimir","title":"the Crimson Reaper"},
"volibear":{"id":106,"name":"Volibear","internalName":"Volibear","title":"the Thunder's Roar"},
"warwick":{"id":19,"name":"Warwick","internalName":"Warwick","title":"the Uncaged Wrath of Zaun"},
"xayah":{"id":498,"name":"Xayah","internalName":"Xayah","title":"the Rebel"},
"xerath":{"id":101,"name":"Xerath","internalName":"Xerath","title":"the Magus Ascendant"},
"xinzhao":{"id":5,"name":"Xin Zhao","internalName":"XinZhao","title":"the Seneschal of Demacia"},
"yasuo":{"id":157,"name":"Yasuo","internalName":"Yasuo","title":"the Unforgiven"},
"yorick":{"id":83,"name":"Yorick","internalName":"Yorick","title":"Shepherd of Souls"},
"zac":{"id":154,"name":"Zac","internalName":"Zac","title":"the Secret Weapon"},
"zed":{"id":238,"name":"Zed","internalName":"Zed","title":"the Master of Shadows"},
"ziggs":{"id":115,"name":"Ziggs","internalName":"Ziggs","title":"the Hexplosives Expert"},
"zilean":{"id":26,"name":"Zilean","internalName":"Zilean","title":"the Chronokeeper"},
"zoe":{"id":142,"name":"Zoe","internalName":"Zoe","title":"the Aspect of Twilight"},
"zyra":{"id":143,"name":"Zyra","internalName":"Zyra","title":"Rise of the Thorns"}
}