var champData = {
    test: "testing"
};
/*
var champData = {
"266": {"name":"Aatrox","internalName":"Aatrox","title":"the Darkin Blade"},
"103": {"name":"Ahri","internalName":"Ahri","title":"the Nine-Tailed Fox"},
"84": {"name":"Akali","internalName":"Akali","title":"the Rogue Assassin"},
"12": {"name":"Alistar","internalName":"Alistar","title":"the Minotaur"},
"32": {"name":"Amumu","internalName":"Amumu","title":"the Sad Mummy"},
"34": {"name":"Anivia","internalName":"Anivia","title":"the Cryophoenix"},
"1": {"name":"Annie","internalName":"Annie","title":"the Dark Child"},
"22": {"name":"Ashe","internalName":"Ashe","title":"the Frost Archer"},
"136": {"name":"Aurelion Sol","internalName":"AurelionSol","title":"The Star Forger"},
"268": {"name":"Azir","internalName":"Azir","title":"the Emperor of the Sands"},
"432": {"name":"Bard","internalName":"Bard","title":"the Wandering Caretaker"},
"53": {"name":"Blitzcrank","internalName":"Blitzcrank","title":"the Great Steam Golem"},
"63": {"name":"Brand","internalName":"Brand","title":"the Burning Vengeance"},
"201": {"name":"Braum","internalName":"Braum","title":"the Heart of the Freljord"},
"51": {"name":"Caitlyn","internalName":"Caitlyn","title":"the Sheriff of Piltover"},
"164": {"name":"Camille","internalName":"Camille","title":"the Steel Shadow"},
"69": {"name":"Cassiopeia","internalName":"Cassiopeia","title":"the Serpent's Embrace"},
"31": {"name":"Cho'Gath","internalName":"Chogath","title":"the Terror of the Void"},
"42": {"name":"Corki","internalName":"Corki","title":"the Daring Bombardier"},
"122": {"name":"Darius","internalName":"Darius","title":"the Hand of Noxus"},
"131": {"name":"Diana","internalName":"Diana","title":"Scorn of the Moon"},
"119": {"name":"Draven","internalName":"Draven","title":"the Glorious Executioner"},
"36": {"name":"Dr. Mundo","internalName":"DrMundo","title":"the Madman of Zaun"},
"245": {"name":"Ekko","internalName":"Ekko","title":"the Boy Who Shattered Time"},
"60": {"name":"Elise","internalName":"Elise","title":"the Spider Queen"},
"28": {"name":"Evelynn","internalName":"Evelynn","title":"Agony's Embrace"},
"81": {"name":"Ezreal","internalName":"Ezreal","title":"the Prodigal Explorer"},
"9": {"name":"Fiddlesticks","internalName":"Fiddlesticks","title":"the Harbinger of Doom"},
"114": {"name":"Fiora","internalName":"Fiora","title":"the Grand Duelist"},
"105": {"name":"Fizz","internalName":"Fizz","title":"the Tidal Trickster"},
"3": {"name":"Galio","internalName":"Galio","title":"the Colossus"},
"41": {"name":"Gangplank","internalName":"Gangplank","title":"the Saltwater Scourge"},
"86": {"name":"Garen","internalName":"Garen","title":"The Might of Demacia"},
"150": {"name":"Gnar","internalName":"Gnar","title":"the Missing Link"},
"79": {"name":"Gragas","internalName":"Gragas","title":"the Rabble Rouser"},
"104": {"name":"Graves","internalName":"Graves","title":"the Outlaw"},
"120": {"name":"Hecarim","internalName":"Hecarim","title":"the Shadow of War"},
"74": {"name":"Heimerdinger","internalName":"Heimerdinger","title":"the Revered Inventor"},
"420": {"name":"Illaoi","internalName":"Illaoi","title":"the Kraken Priestess"},
"39": {"name":"Irelia","internalName":"Irelia","title":"the Blade Dancer"},
"427": {"name":"Ivern","internalName":"Ivern","title":"the Green Father"},
"40": {"name":"Janna","internalName":"Janna","title":"the Storm's Fury"},
"59": {"name":"Jarvan IV","internalName":"JarvanIV","title":"the Exemplar of Demacia"},
"24": {"name":"Jax","internalName":"Jax","title":"Grandmaster at Arms"},
"126": {"name":"Jayce","internalName":"Jayce","title":"the Defender of Tomorrow"},
"202": {"name":"Jhin","internalName":"Jhin","title":"the Virtuoso"},
"222": {"name":"Jinx","internalName":"Jinx","title":"the Loose Cannon"},
"145": {"name":"Kai'Sa","internalName":"Kaisa","title":"Daughter of the Void"},
"429": {"name":"Kalista","internalName":"Kalista","title":"the Spear of Vengeance"},
"43": {"name":"Karma","internalName":"Karma","title":"the Enlightened One"},
"30": {"name":"Karthus","internalName":"Karthus","title":"the Deathsinger"},
"38": {"name":"Kassadin","internalName":"Kassadin","title":"the Void Walker"},
"55": {"name":"Katarina","internalName":"Katarina","title":"the Sinister Blade"},
"10": {"name":"Kayle","internalName":"Kayle","title":"The Judicator"},
"141": {"name":"Kayn","internalName":"Kayn","title":"the Shadow Reaper"},
"85": {"name":"Kennen","internalName":"Kennen","title":"the Heart of the Tempest"},
"121": {"name":"Kha'Zix","internalName":"Khazix","title":"the Voidreaver"},
"203": {"name":"Kindred","internalName":"Kindred","title":"The Eternal Hunters"},
"240": {"name":"Kled","internalName":"Kled","title":"the Cantankerous Cavalier"},
"96": {"name":"Kog'Maw","internalName":"KogMaw","title":"the Mouth of the Abyss"},
"7": {"name":"LeBlanc","internalName":"Leblanc","title":"the Deceiver"},
"64": {"name":"Lee Sin","internalName":"LeeSin","title":"the Blind Monk"},
"89": {"name":"Leona","internalName":"Leona","title":"the Radiant Dawn"},
"127": {"name":"Lissandra","internalName":"Lissandra","title":"the Ice Witch"},
"236": {"name":"Lucian","internalName":"Lucian","title":"the Purifier"},
"117": {"name":"Lulu","internalName":"Lulu","title":"the Fae Sorceress"},
"99": {"name":"Lux","internalName":"Lux","title":"the Lady of Luminosity"},
"54": {"name":"Malphite","internalName":"Malphite","title":"Shard of the Monolith"},
"90": {"name":"Malzahar","internalName":"Malzahar","title":"the Prophet of the Void"},
"57": {"name":"Maokai","internalName":"Maokai","title":"the Twisted Treant"},
"11": {"name":"Master Yi","internalName":"MasterYi","title":"the Wuju Bladesman"},
"21": {"name":"Miss Fortune","internalName":"MissFortune","title":"the Bounty Hunter"},
"62": {"name":"Wukong","internalName":"MonkeyKing","title":"the Monkey King"},
"82": {"name":"Mordekaiser","internalName":"Mordekaiser","title":"the Iron Revenant"},
"25": {"name":"Morgana","internalName":"Morgana","title":"Fallen Angel"},
"267": {"name":"Nami","internalName":"Nami","title":"the Tidecaller"},
"75": {"name":"Nasus","internalName":"Nasus","title":"the Curator of the Sands"},
"111": {"name":"Nautilus","internalName":"Nautilus","title":"the Titan of the Depths"},
"76": {"name":"Nidalee","internalName":"Nidalee","title":"the Bestial Huntress"},
"56": {"name":"Nocturne","internalName":"Nocturne","title":"the Eternal Nightmare"},
"20": {"name":"Nunu & Willump","internalName":"Nunu","title":"the Boy and His Yeti"},
"2": {"name":"Olaf","internalName":"Olaf","title":"the Berserker"},
"61": {"name":"Orianna","internalName":"Orianna","title":"the Lady of Clockwork"},
"516": {"name":"Ornn","internalName":"Ornn","title":"The Fire below the Mountain"},
"80": {"name":"Pantheon","internalName":"Pantheon","title":"the Artisan of War"},
"78": {"name":"Poppy","internalName":"Poppy","title":"Keeper of the Hammer"},
"555": {"name":"Pyke","internalName":"Pyke","title":"the Bloodharbor Ripper"},
"133": {"name":"Quinn","internalName":"Quinn","title":"Demacia's Wings"},
"497": {"name":"Rakan","internalName":"Rakan","title":"The Charmer"},
"33": {"name":"Rammus","internalName":"Rammus","title":"the Armordillo"},
"421": {"name":"Rek'Sai","internalName":"RekSai","title":"the Void Burrower"},
"58": {"name":"Renekton","internalName":"Renekton","title":"the Butcher of the Sands"},
"107": {"name":"Rengar","internalName":"Rengar","title":"the Pridestalker"},
"92": {"name":"Riven","internalName":"Riven","title":"the Exile"},
"68": {"name":"Rumble","internalName":"Rumble","title":"the Mechanized Menace"},
"13": {"name":"Ryze","internalName":"Ryze","title":"the Rune Mage"},
"113": {"name":"Sejuani","internalName":"Sejuani","title":"Fury of the North"},
"35": {"name":"Shaco","internalName":"Shaco","title":"the Demon Jester"},
"98": {"name":"Shen","internalName":"Shen","title":"the Eye of Twilight"},
"102": {"name":"Shyvana","internalName":"Shyvana","title":"the Half-Dragon"},
"27": {"name":"Singed","internalName":"Singed","title":"the Mad Chemist"},
"14": {"name":"Sion","internalName":"Sion","title":"The Undead Juggernaut"},
"15": {"name":"Sivir","internalName":"Sivir","title":"the Battle Mistress"},
"72": {"name":"Skarner","internalName":"Skarner","title":"the Crystal Vanguard"},
"37": {"name":"Sona","internalName":"Sona","title":"Maven of the Strings"},
"16": {"name":"Soraka","internalName":"Soraka","title":"the Starchild"},
"50": {"name":"Swain","internalName":"Swain","title":"the Noxian Grand General"},
"134": {"name":"Syndra","internalName":"Syndra","title":"the Dark Sovereign"},
"223": {"name":"Tahm Kench","internalName":"TahmKench","title":"the River King"},
"163": {"name":"Taliyah","internalName":"Taliyah","title":"the Stoneweaver"},
"91": {"name":"Talon","internalName":"Talon","title":"the Blade's Shadow"},
"44": {"name":"Taric","internalName":"Taric","title":"the Shield of Valoran"},
"17": {"name":"Teemo","internalName":"Teemo","title":"the Swift Scout"},
"412": {"name":"Thresh","internalName":"Thresh","title":"the Chain Warden"},
"18": {"name":"Tristana","internalName":"Tristana","title":"the Yordle Gunner"},
"48": {"name":"Trundle","internalName":"Trundle","title":"the Troll King"},
"23": {"name":"Tryndamere","internalName":"Tryndamere","title":"the Barbarian King"},
"4": {"name":"Twisted Fate","internalName":"TwistedFate","title":"the Card Master"},
"29": {"name":"Twitch","internalName":"Twitch","title":"the Plague Rat"},
"77": {"name":"Udyr","internalName":"Udyr","title":"the Spirit Walker"},
"6": {"name":"Urgot","internalName":"Urgot","title":"the Dreadnought"},
"110": {"name":"Varus","internalName":"Varus","title":"the Arrow of Retribution"},
"67": {"name":"Vayne","internalName":"Vayne","title":"the Night Hunter"},
"45": {"name":"Veigar","internalName":"Veigar","title":"the Tiny Master of Evil"},
"161": {"name":"Vel'Koz","internalName":"Velkoz","title":"the Eye of the Void"},
"254": {"name":"Vi","internalName":"Vi","title":"the Piltover Enforcer"},
"112": {"name":"Viktor","internalName":"Viktor","title":"the Machine Herald"},
"8": {"name":"Vladimir","internalName":"Vladimir","title":"the Crimson Reaper"},
"106": {"name":"Volibear","internalName":"Volibear","title":"the Thunder's Roar"},
"19": {"name":"Warwick","internalName":"Warwick","title":"the Uncaged Wrath of Zaun"},
"498": {"name":"Xayah","internalName":"Xayah","title":"the Rebel"},
"101": {"name":"Xerath","internalName":"Xerath","title":"the Magus Ascendant"},
"5": {"name":"Xin Zhao","internalName":"XinZhao","title":"the Seneschal of Demacia"},
"157": {"name":"Yasuo","internalName":"Yasuo","title":"the Unforgiven"},
"83": {"name":"Yorick","internalName":"Yorick","title":"Shepherd of Souls"},
"154": {"name":"Zac","internalName":"Zac","title":"the Secret Weapon"},
"238": {"name":"Zed","internalName":"Zed","title":"the Master of Shadows"},
"115": {"name":"Ziggs","internalName":"Ziggs","title":"the Hexplosives Expert"},
"26": {"name":"Zilean","internalName":"Zilean","title":"the Chronokeeper"},
"142": {"name":"Zoe","internalName":"Zoe","title":"the Aspect of Twilight"},
"143": {"name":"Zyra","internalName":"Zyra","title":"Rise of the Thorns"}
};
*/